version: '3.8'

services:
  postgres:
    image: postgis/postgis:latest
    container_name: postgis_container
    environment:
      POSTGRES_DB: damage-detection
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "35432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
